In [1]:
#Import necessary libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

In [2]:
#Load the data set

colors=pd.read_csv("color.csv")
colors.head()

  colors  red  green  blue
0   Blue   20    139   240
1  Brown  174     83    72
2  Green  144    249   131
3   Pink  168     25   156
4  Green   30    182   136

In [3]:
colors.shape

(5052, 4)

In [4]:
colors.columns

Index(['colors', 'red', 'green', 'blue'], dtype='object')

In [5]:
#Convert Categorical Data into Numerical

from sklearn.preprocessing import LabelEncoder
colors["colors"]=LabelEncoder().fit_transform(colors["colors"])
colors.head()

   colors  red  green  blue
0       1   20    139   240
1       2  174     83    72
2       3  144    249   131
3       6  168     25   156
4       3   30    182   136

In [6]:
#Check features correlation

plt.figure(figsize=(6, 4))
sns.heatmap(colors.corr(), annot=True, fmt='.1f', cmap='Blues')
plt.tight_layout()

In [7]:
#Extraction of features (X) and labels (y) from the data set

X = colors[['red', 'green', 'blue']]
y = colors['colors']

In [8]:
X.head()

   red  green  blue
0   20    139   240
1  174     83    72
2  144    249   131
3  168     25   156
4   30    182   136

In [9]:
y.head()

0    1
1    2
2    3
3    6
4    3
Name: colors, dtype: int64

In [10]:
#Split the data into train and test

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
)

In [11]:
#Check the accuracy of the trained model

#KNN model
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
y_pred_knn = knn.predict(X_test)
knn_accuracy = accuracy_score(y_test, y_pred_knn) * 100
print(f"KNN accuracy: {knn_accuracy:.2f}%")

#Random Forest Classifier
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)
rf_accuracy = accuracy_score(y_test, y_pred_rf) * 100
print(f"Random Forest accuracy: {rf_accuracy:.2f}%")

#Decision Tree Classifier
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)
dt_accuracy = accuracy_score(y_test, y_pred_dt) * 100
print(f"Decision Tree accuracy: {dt_accuracy:.2f}%")

#SVC
svc = SVC()
svc.fit(X_train, y_train)
y_pred_svc = svc.predict(X_test)
svc_accuracy = accuracy_score(y_test, y_pred_svc) * 100
print(f"SVC accuracy: {svc_accuracy:.2f}%")

KNN accuracy: 86.15%

Random Forest accuracy: 85.95%
Decision Tree accuracy: 82.59%

SVC accuracy: 87.34%